config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :edit_mood
      patch :update_mood
      get :edit_vacation
      patch :update_vacation
      get :edit_life_choice
      patch :update_life_choice
    end
    resources :likes, only: [:create]
  end

  resources :likes, only: [:create]

  resources :matches, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :events, only: [:index, :show] do
    member do
      patch :send_event
    end
  end
  get "profil", to: "pages#profil", as: :profil

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  MOODS = ["cosy", "drink", "party_night", "museum"]
  VACATIONS = ["montagne", "plage", "city", "foret"]
  LIFE_CHOICES = ["famille", "amour", "argent", "travail"]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_one_attached :mood_image
  has_one_attached :vacation_image
  has_one_attached :life_image
  # has_many_attached :photos

  has_many :messages, dependent: :destroy

  has_many :matches_as_first_user, class_name: 'Match', foreign_key: 'first_user_id', dependent: :destroy
  has_many :matches_as_second_user, class_name: 'Match', foreign_key: 'second_user_id', dependent: :destroy

  has_many :likes_as_liker, class_name: 'Like', foreign_key: 'liker_id', dependent: :destroy
  has_many :likes_as_liked, class_name: 'Like', foreign_key: 'liked_id', dependent: :destroy

  has_many :user_events, dependent: :destroy
  has_many :events, through: :user_events

  # validates :age, presence: true, comparison: { greater_than_or_equal_to: 18 }
  # validates :friends_age, presence: true, comparison: { greater_than_or_equal_to: 18 }
  # validates :name, presence: true
  # validates :language, presence: true
  # validates :location, presence: true
  # validates :genre, presence: true
  # validates :situation, presence: true
  # validates :avatar, presence: true
  # validates :photos, presence: true
  # validates :mood, presence: true, inclusion: { in: MOODS }
  # validates :vacation, presence: true
  # validates :life_choice, presence: true


  def all_matches
    matches_as_first_user + matches_as_second_user
  end


  def suggested_profiles
    User.where.not(id: self.id)
              .where(
                "mood = :mood OR vacation = :vacation OR life_choice = :life_choice",
                mood: mood, vacation: vacation, life_choice: life_choice
              )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:index]

  def index
    @users = User.where.not(id: current_user)
    liked_users = User.joins(:likes_as_liked).where(likes_as_liked: { liker: current_user })
    @users -= liked_users
    @users = current_user.suggested_profiles
  end

  def edit_mood
  end

  def update_mood
    @user.update(mood_params)
    redirect_to edit_vacation_user_path(@user)
  end

  def edit_vacation
  end

  def update_vacation
    @user.update(vacation_params)
    redirect_to edit_life_choice_user_path(@user)
  end

  def edit_life_choices
  end

  def update_life_choice
    @user.update(life_choice_params)
    redirect_to profil_path
    # redirect_to user_path(@user)
  end

  def new
  end

  def show
  end

  def suggestions
    current_user.suggested_profiles
  end

  # def likes
  #   @liked_user = User.find(params[:id])
  #   current_user.likes_given.create(liked_id: @liked_user.id)

  #   respond_to do |format|
  #     format.html { redirect_to users_path, notice: "Vous avez aimé #{@liked_user.name} !" }
  #     format.json { render json: { status: 'success', liked_user: @liked_user } }
  #   end
  #end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def mood_params
    params.require(:user).permit(:mood)
  end

  def vacation_params
    params.require(:user).permit(:vacation)
  end

  def life_choice_params
    params.require(:user).permit(:life_choice)
  end
end

app/views/users/_choice_label.html.erb
<%
  image_url = case choice
  when "cosy" then "flashcard_mood_#{choice}.jpg"
  when "drink" then "flashcard_mood_#{choice}.jpg"
  when "party_night" then "flashcard_mood_#{choice}.jpg"
  when "museum" then "flashcard_mood_#{choice}.jpg"
  when "montagne" then "flashcard_vacances_#{choice}.jpg"
  when "plage" then "flashcard_vacances_#{choice}.jpg"
  when "city" then "flashcard_vacances_#{choice}.jpg"
  when "foret" then "flashcard_vacances_#{choice}.jpg"
  when "famille" then "flashcard_interest_#{choice}.jpg"
  when "amour" then "flashcard_interest_#{choice}.jpg"
  when "argent" then "flashcard_interest_#{choice}.jpg"
  when "travail" then "flashcard_interest_#{choice}.jpg"
  end
%>

<div class="choice-label">
  <%= image_tag image_url, alt: choice %>
</div>

app/views/users/edit_life_choice.html.erb
<%# <div class="profile-container"> %>
  <h1>Choose your priority</h1>

  <%= simple_form_for(@user, url: update_life_choice_user_path(@user), method: :patch, html: { data: { turbo_method: :patch }}) do |f| %>
    <%= f.input :life_choice,
      collection: User::LIFE_CHOICES,
      as: :radio_buttons,
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'choices-wrapper',
      label_method: lambda { |choice| render 'users/choice_label', choice: choice },
      item_wrapper_class: 'choices-item',
      input_html: { class: 'choices-selector' } %>
    <div class="d-flex justify-content-center">
      <%= f.submit "next", class: "btn btn-primary next-btn" %>
    <%# </div> %>
  <% end %>

app/views/users/edit_mood.html.erb
 <%# <div class="profile-container"> %>
  <h1>Choose your mood</h1>

  <%= simple_form_for(@user, url: update_mood_user_path(@user), method: :patch, html: { data: { turbo_method: :patch }}) do |f| %>
    <%= f.input :mood,
      collection: User::MOODS,
      as: :radio_buttons,
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'choices-wrapper',
      label_method: lambda { |choice| render 'users/choice_label', choice: choice },
      item_wrapper_class: 'choices-item',
      input_html: { class: 'choices-selector' } %>
    <div class="d-flex justify-content-center">
      <%= f.submit "NEXT", class: "btn btn-primary next-btn" %>
    </div>
  <% end %>
<%# </div> %>

app/views/users/edit_vacation.html.erb
<%# <div class="profile-container"> %>
  <h1>Choose your vacation</h1>

  <%= simple_form_for(@user, url: update_vacation_user_path(@user), method: :patch, html: { data: { turbo_method: :patch }}) do |f| %>
    <%= f.input :vacation,
      collection: User::VACATIONS,
      as: :radio_buttons,
      collection_wrapper_tag: 'div',
      collection_wrapper_class: 'choices-wrapper',
      label_method: lambda { |choice| render 'users/choice_label', choice: choice },
      item_wrapper_class: 'choices-item',
      input_html: { class: 'choices-selector' } %>
    <div class="d-flex justify-content-center">
      <%= f.submit "next", class: "btn btn-primary next-btn" %>
    </div>
  <% end %>

<%# </div> %>

app/views/users/index.html.erb
<div class="swiper w-100" data-controller="swipe coordinates confetti" data-action="swipe:match->confetti#sendConfetti" data-confetti-duration-value=1000>
  <div class="swiper__content">
    <div class="swiper__card-cont">
      <% @users.each do |user| %>
        <div class="swiper__card "
              data-swipe-target="card"
              data-id="<%= user.id %>"
              data-current="<%= current_user.id %>"
              >
          <div class="swiper__card__content">

            <div class="swiper__card__content_top">

            </div>
            <div class="avatar-profil mb-2">
              <%= image_tag user.avatar_url, class: 'swiper__card__img rounded-circle w-100 h-100 object-fit-cover' %>
            </div>


            <div class="name mt-2">
              <h2><%= user.name %></h2>
            </div>

            <div class="stats-container">
              <div class="grid-symp">
                <div class="stats-item">
                  <i class="fa-solid fa-cake-candles"></i><p><%= user.age %></p>

                </div>
                <div class="stats-item">
                  <i class="fa-solid fa-location-dot"></i><p>5 KM</p>
                </div>
              </div>
              <div class="stats-item">
                <i class="fa-solid fa-globe"></i><p><%= user.language %></p>
              </div>
            </div>


            <section>
              <div class="container swiper-custom-container">
                <div class="answers">
                  <!-- Image 1 -->
                  <div class="col-12 col-md-3">
                    <div class="">
                      <%= image_tag "flashcard_mood_#{user.mood}.jpg", class: "img-fluid", style: "border-radius: 10px; height: 120px; width: 108px", alt: user.mood unless user.mood.nil? %>
                      <%#= cl_image_tag user.mood_image.key, class: "img-fluid", alt: user.mood, style: "border-radius: 10px; height: 180px; width: 108px" %>
                    </div>
                  </div>

                  <div class="col-12 col-md-3">
                    <div class="">
                      <%= image_tag "flashcard_interest_#{user.life_choice}.jpg", class: "img-fluid", style: "border-radius: 10px; height: 120px; width: 108px", alt: user.life_choice unless user.life_choice.nil? %>
                      <%#= cl_image_tag user.vacation_image.key, class: "img-fluid", alt: user.vacation, style: "border-radius: 10px; height: 180px; width: 108px" %>
                    </div>
                  </div>

                  <div class="col-12 col-md-3">
                    <div class="">
                      <%= image_tag "flashcard_vacances_#{user.vacation}.jpg", class: "img-fluid", style: "border-radius: 10px; height: 120px; width: 108px", alt: user.vacation unless user.vacation.nil? %>
                      <%#= cl_image_tag user.life_image.key, class: "img-fluid", alt: user.life_choice, style: "border-radius: 10px; height: 180px; width: 108px" %>
                    </div>
                  </div>

                </div>
              </div>
            </section>



            <div class="events-title">
              <h5>Events</h5>
            </div>
            <div class="events-container">
              <div class="event-item">
                <div class="event-icon event1"></div>
                <p class="event-text">Beach volley match</p>
              </div>
              <div class="event-item">
                <div class="event-icon event2"></div>
                <p class="event-text">Latino Party at Salsero</p>
              </div>
              <div class="event-item">
                <div class="event-icon event3"></div>
                <p class="event-text">Party at Cabaret Sauvage</p>
              </div>
            </div>

            <div class="swiper__card__content_bottom">
              <p class="swiper__card__name"></p>
              <p class="swiper__card__distance"></p>
            </div>

          </div>
          <div class="swiper__card__choice m--reject"></div>
          <div class="swiper__card__choice m--like"></div>
          <div class="swiper__card__drag"></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="modal fade matches" data-swipe-target="modal" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog success-modal-dialog top-30">
      <div class="modal-content success-modal-content">
        <div class="modal-body success-modal-body body-better" data-swipe-target="modalBody"></div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%# flashcards %>

app/views/users/show.html.erb
<%= link_to "Leave", destroy_user_session_path, class: "d-block mt-5 p-5", data: { turbo_method: :delete } %>


<h2>Mood</h2>

<% mood_url = case current_user.mood
  when "cosy" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723362/flashcard_mood_jrkyzo.jpg"
  when "drink" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723114/flashcard_mood_bar_warrp5.jpg"
  when "party_night" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723114/flashcard_mood_fete_lesxj8.jpg"
  when "museum" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723114/flashcard_mood_musee_fkcqae.jpg"
  end
%>

<%= image_tag mood_url %>


<h2><%= current_user.life_choice %> </h2>

<% vacation_url = case current_user.vacation
  when "montagne" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723116/flashcard_vacances_montagne_hc31lz.jpg"
  when "plage" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723116/flashcard_vacances_mer_snd8ic.jpg"
  when "city" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723116/flashcard_vacances_ville_hup7qb.jpg"
  when "foret" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723115/flashcard_vacances_foret_yff6lv.jpg"
  end
%>

<%= image_tag vacation_url %>

<h2>Life Choice</h2>

<% life_choice_url = case current_user.life_choice
  when "famille" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723113/flashcard_interest_famille_blhbzy.jpg"
  when "amour" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723093/flashcard_interest_amour_fyguqm.jpg"
  when "argent" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723113/flashcard_interest_money_optozh.jpg"
  when "travail" then "https://res.cloudinary.com/dxhdcwxy0/image/upload/v1732723114/flashcard_interest_pro_2_afeocc.jpg"
  end
%>

<%= image_tag life_choice_url%>