config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :edit, :update] do
    member do
      get :edit_mood
      patch :update_mood
      get :edit_vacation
      patch :update_vacation
      get :edit_life_choice
      patch :update_life_choice
    end
    resources :likes, only: [:create]
  end

  resources :likes, only: [:create]

  resources :matches, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :events, only: [:index, :show] do
    member do
      patch :send_event
    end
  end
  get "profil", to: "pages#profil", as: :profil

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :photo

  has_many :user_events
  has_many :users, through: :user_events

  has_many :event_categories
  has_many :categories, through: :event_categories
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @matches = Match.all
    @user = current_user
    @user_events = @user.events
  end

  def send_event
    @event = Event.find(params[:id])
    send_event_params[:match_ids].each do |id|
      next if id == ""

      match = Match.find(id)
      Message.create(
        match: match,
        user: current_user,
        content: "I am participating to #{@event.title}, do you want to join me?"
      )
    end
    redirect_to events_path, alert: "Events succesfully shared!"

  end

  private

  def send_event_params
    params.require(:send_event).permit(match_ids: [])
  end
end

app/views/events/index.html.erb
<div class="all-events-cards">
  <% @events.each do |event| %>
    <div class="card-event">
      <img src="<%= event.image_url %>" alt="<%= event.title %>" />

      <div class="card-event-infos">
        <div class="card-event-details inter-regular">
          <h2 class= "impact-regular"><%= event.title %></h2>
          <p class="card-event-description"><%= event.description %></p>
          <p class="card-event-date"><%= event.date.strftime("%B, %d %Y") %></p>
          <p class="card-event-location"><%= event.location %></p>
        </div>

        <h2 class="card-event-pricing inter-regular"><%= event.price %> €</h2>
      </div>

      <div class="buttons">
        <p class="btn-join button bebas-neue-regular" data-controller="join" data-action="click->join#click" data-events-target="JoinButton">
          <i class="fa-solid fa-user" style="color: #ffffff;"></i> Join the event
        </p>

        <button type="button" class="btn-share button bebas-neue-regular" data-bs-toggle="modal" data-bs-target="#exampleModal">
          <i class="fa-solid fa-paper-plane" style="color: #ffffff;"></i> Share
        </button>
      </div>

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <%= simple_form_for :send_event, url: send_event_event_path(event), method: :patch do |f| %>
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title bebas-neue-regular" id="exampleModalLabel">Who would you like to share this event with?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body inter-regular">
            <%= f.input :match_ids,
                title: false,
                input_html: { class:"ma-classe" },

                collection: current_user.all_matches,
                as: :check_boxes,
                value_method: ->(match) { match.id },
                label_method: ->(match) {
                  content_tag(:div) do
                    content_tag(:p, match.other_user(current_user).name, style: "margin-bottom: 0")
                  end

                },
                wrapper: false,
                label: "Select one or more matches:",
                required: false
        %>
            </div>
            <div class="modal-footer">
            <div class="button-event-container">
              <%= button_tag type: "submit", class: "button-event bebas-neue-regular", style: "padding: 8px 16px; font-size: 16px; flex: 1;" do %> <i class="fa-solid fa-user" style="color: #ffffff; margin-right: 8px;"></i> Share events <% end %>
            </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>